// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrbFZa7Y-H7nxwx2B8gNbaPdpPZyRevQ',
    appId: '1:759377425085:web:27286c4b1de8846d4b3dd4',
    messagingSenderId: '759377425085',
    projectId: 'name-64dc7',
    authDomain: 'name-64dc7.firebaseapp.com',
    storageBucket: 'name-64dc7.appspot.com',
    measurementId: 'G-1S29Z5Z13E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8UOYwsBamScLD-sUh7tBbP3tDADXiKg',
    appId: '1:759377425085:android:dfad104191114f174b3dd4',
    messagingSenderId: '759377425085',
    projectId: 'name-64dc7',
    storageBucket: 'name-64dc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5O8sFch4IDbK1tdNv326se2S7phh6knA',
    appId: '1:759377425085:ios:7bb8050ea733b9fe4b3dd4',
    messagingSenderId: '759377425085',
    projectId: 'name-64dc7',
    storageBucket: 'name-64dc7.appspot.com',
    iosBundleId: 'com.example.name',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5O8sFch4IDbK1tdNv326se2S7phh6knA',
    appId: '1:759377425085:ios:d157d5eb36510e694b3dd4',
    messagingSenderId: '759377425085',
    projectId: 'name-64dc7',
    storageBucket: 'name-64dc7.appspot.com',
    iosBundleId: 'com.example.name.RunnerTests',
  );
}
