// pattent_for_contents
// 'courses1': [
//    1. "image_url"
//    2. "course name"
//    3. "author name"
//    4. "ratings"
//    5. "amount",
//    6. "preview image\"
//    7. "total lessons"
//    8.  "total_hours needed to cover the topic",
//    9. "Liked or disliked" (str)
//    10. "description" (tes)
//    11. enrolled or not enrolled (stu)
//    12. cart or not in (stu)
//    13. atlast follow categories fall in
//   ],

Map<String, List> coursesList = {
  'courses1': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData[0]],
  ],
  'courses2': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData[3]],
  ],
  'courses3': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData.last],
  ],
  'courses4': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData.last],
  ],
  'courses5': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData[2]],
  ],
  'courses6': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData.last],
  ],
  'courses7': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData[5]],
  ],
  'courses8': [
    "image_url",
    "Invest Money Wisely",
    "Effective Code Learning",
    "5.0",
    "\$100.0",
    "preview image",
    "15",
    "15 Hours",
    true,
    ' This course is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!is about how you can invest money wisely and make it grow with time  It will teach you how to code in a way that makes your money work for you.Youl learn how to write effective codes that will help you achieve financial freedom This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity. Enroll now!It will teach you how to code in a way that makes your money work for you. Youll learn how to write effective codes that will help you achieve financial freedom. This course will also give you insights into market trends so that you can make wise decisions. Dont miss out on this opportunity Enroll now!',
    true,
    true,
    [chipData.first, chipData[1]],
  ],
};

List<String> chipData = [
  "All Courses",
  "Programming",
  "Finance",
  "Music",
  "Health",
  "Marketing"
];
